import type { Metadata } from 'next';
import PageTransition from '@/components/PageTransition';

export const metadata: Metadata = {
  title: 'Terms & Conditions — Qualisense',
  description: 'Terms and conditions governing access to and use of the Qualisense website, applications and services.',
};

const SECTIONS: { title: string; content: React.ReactNode }[] = [
  {
    title: '1. About these Terms',
    content: (
      <>
        <p className="terms-text">
          These Terms and Conditions ("Terms") form a binding agreement between Graphiti Research Technologies Private Limited, a company incorporated under the laws of Haryana, India, with its registered office at 814 Galleria Office Tower, DLF Phase 4, Gurgaon, Haryana, India 122009 ("Qualisense", "we", "us" or "our"), and the individual or organisation accessing or using the Service ("Customer", "you" or "your").
        </p>
        <p className="terms-text">
          By creating an account, accepting an Order Form, clicking to accept these Terms, or using the Service, you agree to these Terms. If you use the Service on behalf of an organisation, you represent that you have authority to bind that organisation.
        </p>
        <p className="terms-text">
          If an Order Form, statement of work, Data Processing Addendum ("DPA") or other written agreement conflicts with these Terms, the following order of precedence applies unless the document states otherwise: (1) Order Form; (2) DPA for data-protection matters; (3) statement of work; and (4) these Terms.
        </p>
      </>
    ),
  },
  {
    title: '2. Key definitions',
    content: (
      <ul className="terms-list">
        <li><strong>Customer Content:</strong> Audio, video, transcripts, discussion guides, respondent information, research materials, prompts, project data and other information submitted to or generated through the Service on Customer's behalf.</li>
        <li><strong>Output:</strong> Transcripts, translations, matrices, reports, summaries, classifications, chat responses and other results generated by the Service.</li>
        <li><strong>Service:</strong> The Qualisense website, platform, APIs and features, including discussion-guide automation, live AI interviewing, transcription, translation, structured analysis, report generation, project chat and cross-project querying.</li>
        <li><strong>User:</strong> An individual authorised by Customer to access the Service.</li>
        <li><strong>Respondent:</strong> A research participant, interviewee or other person whose information is processed through the Service.</li>
      </ul>
    ),
  },
  {
    title: '3. Eligibility and business use',
    content: (
      <>
        <p className="terms-text">
          The Service is intended for lawful business and professional use. You must be at least 18 years old and legally capable of entering into a contract. The Service is not intended for direct use by children or consumers acting for personal, family or household purposes.
        </p>
        <p className="terms-text">
          Customer is responsible for ensuring that its Users comply with these Terms and for all activity conducted under its accounts, except to the extent caused by Qualisense's breach of these Terms.
        </p>
      </>
    ),
  },
  {
    title: '4. The Service',
    content: (
      <>
        <p className="terms-text">
          Qualisense provides software-assisted workflows for qualitative research. Depending on the selected plan or Order Form, the Service may include:
        </p>
        <ul className="terms-list">
          <li>Creation or automation of discussion guides</li>
          <li>Live AI-led depth interviews in supported languages</li>
          <li>Transcription and translation of uploaded or generated audio and video</li>
          <li>Organisation of responses into structured analysis matrices</li>
          <li>Generation of reports, themes, comparisons and other research outputs</li>
          <li>Chat-based querying within a project or across selected projects in a workspace</li>
          <li>Optional coordination with independent third-party respondent-recruitment or fieldwork providers</li>
        </ul>
        <p className="terms-text">
          We may improve, modify or discontinue features from time to time. We will not materially reduce the core functionality of a paid subscription during its current term without reasonable notice, except where required for security, legal compliance or prevention of misuse.
        </p>
      </>
    ),
  },
  {
    title: '5. Accounts and access security',
    content: (
      <ul className="terms-list">
        <li>Customer must provide accurate registration and billing information and keep it current.</li>
        <li>Login credentials are personal to each User and may not be shared.</li>
        <li>Customer must use reasonable security measures, including strong passwords and multi-factor authentication where available.</li>
        <li>Customer must promptly notify us at <a href="mailto:contact@quali-sense.ai" className="terms-link">contact@quali-sense.ai</a> of suspected unauthorised access, credential compromise or misuse.</li>
        <li>We may suspend access where reasonably necessary to protect the Service, Customer Content, other customers or third parties.</li>
      </ul>
    ),
  },
  {
    title: '6. Customer Content and ownership',
    content: (
      <>
        <p className="terms-text">
          As between the parties, Customer retains all rights in Customer Content. Customer grants Qualisense and its approved subprocessors a limited, non-exclusive, worldwide right to host, copy, transmit, transform and otherwise process Customer Content only as necessary to provide, secure, support and improve the Service in accordance with these Terms, the DPA and Customer's documented instructions.
        </p>
        <p className="terms-text">
          Qualisense does not acquire ownership of Customer Content. Qualisense will not make Customer Content available to other customers. Qualisense will not use Customer Content to train general-purpose AI models unless Customer expressly opts in or the parties agree in writing. Qualisense may use aggregated and de-identified service telemetry that does not identify Customer, Users or Respondents to operate, secure and improve the Service.
        </p>
        <p className="terms-text">
          Customer represents and warrants that it has all rights, permissions and lawful bases necessary to submit Customer Content and permit its processing under these Terms.
        </p>
      </>
    ),
  },
  {
    title: '7. Respondent data, recordings and live AI interviews',
    content: (
      <>
        <p className="terms-text">Customer determines the research purpose, respondent selection, discussion guide and lawful basis for processing Respondent information. Customer is responsible for:</p>
        <ul className="terms-list">
          <li>Providing appropriate privacy notices and obtaining valid consent or another lawful basis for recording, transcription, translation, analysis and storage</li>
          <li>Clearly informing Respondents when an interview is conducted by or involves an AI system, where required by law or research ethics</li>
          <li>Obtaining any additional consent required for sensitive personal data, special-category data, minors or vulnerable participants</li>
          <li>Ensuring that questions, incentives, recruitment and fieldwork comply with applicable laws, professional codes and Customer policies</li>
          <li>Handling Respondent requests and complaints as the organisation responsible for the research</li>
          <li>Avoiding deceptive, coercive, discriminatory or unsafe research practices</li>
        </ul>
        <p className="terms-text">
          The live interviewing agent is designed for research interviews and is not an emergency service, therapist, doctor, lawyer, financial adviser or crisis-support service. Customer must not configure it to provide professional advice or make decisions that produce legal or similarly significant effects on individuals.
        </p>
      </>
    ),
  },
  {
    title: '8. Acceptable use',
    content: (
      <>
        <p className="terms-text">Customer and Users must not use the Service to:</p>
        <ul className="terms-list">
          <li>Violate applicable law, privacy rights, intellectual-property rights, contractual obligations or professional research standards</li>
          <li>Upload content without required rights, permissions, notices or consents</li>
          <li>Conduct unlawful surveillance, biometric identification, manipulation, impersonation, harassment or discriminatory profiling</li>
          <li>Collect payment-card data, passwords, government identifiers or other high-risk credentials unless expressly supported and agreed in writing</li>
          <li>Generate or distribute malware, spam, unlawful content, deceptive communications or content that facilitates harm</li>
          <li>Reverse engineer, scrape, probe, overload, bypass security controls or attempt unauthorised access to the Service</li>
          <li>Use the Service to build or benchmark a competing product except with our prior written permission</li>
          <li>Remove proprietary notices or misrepresent the source, nature or reliability of an Output</li>
          <li>Use Output as the sole basis for employment, credit, insurance, healthcare, legal, educational, housing or other high-impact decisions about an individual</li>
        </ul>
      </>
    ),
  },
  {
    title: '9. AI-generated Output and human review',
    content: (
      <>
        <p className="terms-text">
          The Service uses automated and artificial-intelligence systems. Outputs may be incomplete, incorrect, inconsistent, biased or unsuitable for a particular purpose. Similar inputs may produce different Outputs.
        </p>
        <p className="terms-text">
          Customer must apply qualified human review before relying on an Output, presenting it to a client, publishing it, or using it to make a decision. Qualisense does not warrant that an Output will replace professional research judgement, accurately represent every Respondent, or meet a particular research, legal or regulatory standard.
        </p>
        <p className="terms-text">
          Customer is responsible for validating quotations, translations, attribution, interpretation, recommendations and factual claims against the underlying source material.
        </p>
      </>
    ),
  },
  {
    title: '10. Third-party services and field providers',
    content: (
      <>
        <p className="terms-text">
          The Service may interoperate with third-party hosting, communications, transcription, AI, payment, analytics and fieldwork providers. Approved data-processing subprocessors will be governed by contractual obligations appropriate to their role.
        </p>
        <p className="terms-text">
          Where Qualisense introduces or coordinates an independent respondent-recruitment or fieldwork provider, that provider may supply services under separate terms. Unless expressly stated in an Order Form, Qualisense is not responsible for the provider's recruitment decisions, respondent conduct, incentive payments, fieldwork quality or independent acts and omissions.
        </p>
      </>
    ),
  },
  {
    title: '11. Fees, subscriptions and taxes',
    content: (
      <ul className="terms-list">
        <li>Fees, usage limits, billing cycles and payment terms are stated in the applicable Order Form or checkout page.</li>
        <li>Fees are exclusive of applicable taxes, duties and levies, which Customer must pay unless a valid exemption applies.</li>
        <li>Subscriptions renew as stated in the Order Form. Customer must give cancellation notice within the stated notice period to avoid renewal.</li>
        <li>Except where required by law or expressly stated in an Order Form, fees are non-refundable and unused credits expire at the end of the applicable period.</li>
        <li>We may suspend paid access for undisputed overdue amounts after reasonable notice.</li>
      </ul>
    ),
  },
  {
    title: '12. Intellectual property',
    content: (
      <>
        <p className="terms-text">
          Qualisense and its licensors own the Service, software, interfaces, workflows, models, documentation, designs, trademarks and all related intellectual-property rights, excluding Customer Content.
        </p>
        <p className="terms-text">
          Subject to payment of fees and compliance with these Terms, Qualisense grants Customer a limited, non-exclusive, non-transferable right during the subscription term to access and use the Service for its internal business purposes and authorised client work.
        </p>
        <p className="terms-text">
          Customer owns its Output to the extent permitted by applicable law, subject to Qualisense's ownership of the underlying Service and any third-party materials. Because AI-generated content may not qualify for exclusive intellectual-property protection and similar Output may be generated for others, Qualisense does not guarantee exclusivity or protectability of Output.
        </p>
        <p className="terms-text">
          If Customer provides feedback, Customer grants Qualisense a perpetual, worldwide, royalty-free right to use that feedback without identifying Customer or disclosing Customer Confidential Information.
        </p>
      </>
    ),
  },
  {
    title: '13. Confidentiality',
    content: (
      <>
        <p className="terms-text">
          Each party may receive non-public information identified as confidential or that reasonably should be understood to be confidential ("Confidential Information"). The receiving party will use Confidential Information only to perform or receive services under the agreement, protect it using reasonable care, and disclose it only to personnel, advisers and contractors who need to know it and are bound by confidentiality obligations.
        </p>
        <p className="terms-text">
          Confidential Information does not include information that is independently developed, lawfully received without restriction, becomes public without breach, or was already known without confidentiality obligations. A party may disclose Confidential Information where legally required after giving notice where lawful.
        </p>
      </>
    ),
  },
  {
    title: '14. Privacy, data protection and security',
    content: (
      <>
        <p className="terms-text">
          Our processing of personal data is described in the{' '}
          <a href="/privacy" className="terms-link">Qualisense Privacy Policy</a>.
          Where Qualisense processes personal data in Customer Content on Customer's behalf, the parties will comply with the DPA and applicable data-protection law.
        </p>
        <p className="terms-text">
          Qualisense will maintain appropriate technical and organisational measures designed to protect Customer Content against unauthorised access, loss, alteration or disclosure. No internet-based service is completely secure, and Customer remains responsible for appropriate access controls, data minimisation, lawful retention and secure use of exported data.
        </p>
        <p className="terms-text">
          Customer must not rely on marketing statements as a substitute for reviewing Qualisense's security documentation, DPA, subprocessor list and any agreed security schedule.
        </p>
      </>
    ),
  },
  {
    title: '15. Service availability, support and beta features',
    content: (
      <>
        <p className="terms-text">
          Service levels, support hours and remedies apply only if stated in an Order Form or service-level agreement. Planned maintenance, emergency maintenance, third-party failures, internet conditions and events outside reasonable control may affect availability.
        </p>
        <p className="terms-text">
          Features labelled beta, preview, pilot, experimental or similar are provided for evaluation, may change or be discontinued, and may have lower reliability or additional limitations. Customer should not use beta features for critical workloads unless expressly agreed.
        </p>
      </>
    ),
  },
  {
    title: '16. Warranties and disclaimers',
    content: (
      <>
        <p className="terms-text">
          Each party warrants that it has authority to enter into the agreement. Qualisense warrants that it will provide paid Services with reasonable skill and care and substantially in accordance with applicable documentation.
        </p>
        <p className="terms-text">
          Except for the express warranty above and to the maximum extent permitted by law, the Service and Outputs are provided "as is" and "as available". Qualisense disclaims implied warranties of merchantability, fitness for a particular purpose, non-infringement, accuracy and uninterrupted or error-free operation. Qualisense does not guarantee any research outcome, commercial result, respondent behaviour or acceptance of Output by Customer's clients or regulators.
        </p>
      </>
    ),
  },
  {
    title: '17. Indemnities',
    content: (
      <p className="terms-text">
        Customer will defend and indemnify Qualisense against third-party claims arising from Customer Content, Customer's research design or fieldwork, failure to obtain required notices or consents, misuse of the Service, or breach of Sections 6 to 9, except to the extent caused by Qualisense's breach.
      </p>
    ),
  },
  {
    title: '18. Limitation of liability',
    content: (
      <>
        <p className="terms-text">
          To the maximum extent permitted by law, neither party will be liable for indirect, incidental, special, consequential, exemplary or punitive damages, or for loss of profits, revenue, goodwill, anticipated savings or business opportunity, even if advised of the possibility.
        </p>
        <p className="terms-text">
          Subject to the paragraph below, each party's total aggregate liability arising out of or relating to the agreement will not exceed the fees paid or payable by Customer for the Service giving rise to the claim during the 12 months immediately preceding the event giving rise to liability.
        </p>
        <p className="terms-text">
          Nothing in these Terms excludes or limits liability that cannot lawfully be excluded, including liability for fraud or fraudulent misrepresentation, death or personal injury caused by negligence, or any other liability that applicable law requires to remain unlimited.
        </p>
      </>
    ),
  },
  {
    title: '19. Suspension and termination',
    content: (
      <>
        <p className="terms-text">
          Either party may terminate an Order Form for material breach if the breach is not cured within 30 days after written notice, or immediately where the breach cannot be cured, the other party becomes insolvent, or continued performance would violate law.
        </p>
        <p className="terms-text">
          Qualisense may suspend access immediately where reasonably necessary to address a security risk, unlawful activity, prohibited use, material harm or a legally binding request. Where practicable, we will give advance notice and limit the suspension to the affected account or feature.
        </p>
        <p className="terms-text">
          On termination, Customer's right to use the Service ends. Customer may export Customer Content during the subscription term and for 30 days after termination, unless legally prohibited or the account is terminated for serious misuse. Qualisense will delete or return Customer Content in accordance with the DPA and documented retention schedule, subject to backups and legal obligations.
        </p>
      </>
    ),
  },
  {
    title: '20. Governing law and disputes',
    content: (
      <>
        <p className="terms-text">
          These Terms are governed by the laws of Haryana, India, without regard to conflict-of-law principles. The parties agree that disputes will be resolved by courts in Haryana, India. Nothing prevents either party from seeking urgent injunctive relief to protect confidentiality, security or intellectual-property rights.
        </p>
        <p className="terms-text">
          Before commencing formal proceedings, the parties will attempt in good faith for at least 30 days to resolve the dispute through authorised business representatives, unless urgent relief is required.
        </p>
      </>
    ),
  },
  {
    title: '21. General terms',
    content: (
      <ul className="terms-list">
        <li>Neither party is liable for delay caused by events beyond its reasonable control, except payment obligations.</li>
        <li>Customer may not assign the agreement without our prior written consent, except as part of a merger, reorganisation or sale of substantially all assets. Qualisense may assign it to an affiliate or successor.</li>
        <li>Notices must be sent to the addresses in the Order Form and to <a href="mailto:contact@quali-sense.ai" className="terms-link">contact@quali-sense.ai</a>.</li>
        <li>Failure to enforce a provision is not a waiver. Invalid provisions will be modified to the minimum extent necessary, and the remaining provisions remain effective.</li>
        <li>The parties are independent contractors. These Terms do not create a partnership, agency, employment or fiduciary relationship.</li>
        <li>The agreement is the complete agreement about the Service and replaces prior discussions on the same subject.</li>
        <li>Headings are for convenience and do not affect interpretation.</li>
      </ul>
    ),
  },
  {
    title: '22. Changes to these Terms',
    content: (
      <p className="terms-text">
        We may update these Terms to reflect changes to the Service, law, security practices or business operations. We will post the revised version with an updated date and provide additional notice where required or where changes materially reduce Customer's rights. Continued use after the effective date constitutes acceptance, except where applicable law or an Order Form requires express agreement.
      </p>
    ),
  },
  {
    title: '23. Contact',
    content: (
      <p className="terms-text">
        Questions about these Terms may be sent to Graphiti Research Technologies Private Limited, 814 Galleria Office Tower, DLF Phase 4, Gurgaon, Haryana, India 122009; email:{' '}
        <a href="mailto:contact@quali-sense.ai" className="terms-link">contact@quali-sense.ai</a>;
        website:{' '}
        <a href="https://graphitirt.com" className="terms-link" target="_blank" rel="noopener noreferrer">graphitirt.com</a>.
      </p>
    ),
  },
];

export default function TermsPage() {
  return (
    <PageTransition>
      <div className="page-hero" style={{ paddingBottom: 0 }}>
        <div className="container">
          <div className="eyebrow">Legal</div>
          <h1 style={{ fontSize: 'clamp(2rem, 4vw, 3.2rem)', marginBottom: 12 }}>
            Terms &amp; Conditions
          </h1>
          <p className="lede" style={{ maxWidth: 640 }}>
            These Terms govern access to and use of the Qualisense website, applications and services. They are designed primarily for business customers, including qualitative research agencies, brands, insights teams, marketing teams and authorised research professionals.
          </p>
          <p style={{ color: 'var(--muted)', fontSize: '.9rem', marginTop: 12 }}>
            Last updated: 16 June 2026
          </p>
        </div>
      </div>

      <section className="section">
        <div className="container">
          <div className="terms-body">
            {SECTIONS.map((section) => (
              <div key={section.title} className="terms-section">
                <h2 className="terms-heading">{section.title}</h2>
                {section.content}
              </div>
            ))}
          </div>
        </div>
      </section>
    </PageTransition>
  );
}
